name: Save HTML

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  save-html:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Save HTML
      env:
        URL: https://policies.google.com/terms?hl=zh-CN&fg=1  # Replace with the URL you want to save
      run: |
        curl "$URL" > google-terms.html
        
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update HTML
        file_pattern: google-terms.html
