name: Save HTML

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  save-html:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Save HTML
      env:
        URL: https://policies.google.com/terms?hl=zh-CN&fg=1  # Replace with the URL you want to save
      run: |
        curl "$URL" > google-terms.html

    - name: Print Working Directory
      run: pwd  # On Unix-like system
        
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update HTML
        file_pattern: '*.html'
